name: build
on: [push]
jobs:
  build-my-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: rm -r dist
      - run: yarn
      - run: yarn run build
